# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            
    access_control:
        
         # English Path
        - { path: ^/en/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/en/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/en/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Français Path
        - { path: ^/fr/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fr/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fr/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/fr/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/fr/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/admin/, role: ROLE_ADMIN }